### ISSUE TITLE
As a Song Manager, I can export a Favourite list as XML

### ISSUE THREAD

**Issue by sskjames** [crunchersaspire/worshipsongs-android#226] opened 2015-11-06 11:48 UTC
NOTE:
- Every song should be in a separate XML file
- A zip file which contains the XML files should be created

**Comment by pitchumani1989** [comment] 2015-11-14 03:36
What is the xml file format, what are the attributes should be available in xml file?

**Comment by GermanGospel** [comment] 2017-02-10 00:25
It would be great, if the OpenLP Service Files (*.osz *.oszl) format would be used. If importing and exporting such files would be possible, that would make this app an perfect partner for the desktop OpenLP software!

**Comment by GermanGospel** [comment] 2017-02-10 00:29
OSZ file: https://forums.openlp.org/discussion/2545/information-about-osz-file

**Comment by sskjames** [comment] 2017-02-21 06:52
This looks like a potential duplicate of #221

**Comment by GermanGospel** [comment] 2017-02-21 08:05
@sskjames - OSZ/OSZL files contain the song lyrics in JSON format. This feature request is for an export option as a XML file. It think OSZL would be the perfect choice!

**Comment by madasamys** [comment] 2017-03-09 06:06
This is a duplicate of #221.

**Closed by madasamys** 2017-03-09 06:06 UTC
Labels: newfeature
